- name: Append a line to docker file to store temps in disk
  lineinfile:
    path: /etc/default/docker
    line: export DOCKER_TMPDIR="{{ STORAGE }}/tmp/docker"
    insertafter: EOF
  tags: docker

- name: Generate compose.yml file and copy it
  template:
    src: compose.yml
    dest: "{{ USER_PATH }}/compose.yml"
  tags: docker, compose, compose-restart, container

- name: Stop Docker
  command: sudo docker-compose down --remove-orphans
  tags: docker, compose-restart

- name: Start Docker
  command: sudo COMPOSE_HTTP_TIMEOUT=200 docker-compose up -d
  tags: docker, compose-restart

- name: Restart Docker Container
  shell: sudo docker-compose restart {{ container }}
  when: container is defined
  tags: container